import type { Ring } from '@/types/ring';

/**
 * リングマスターデータ — 9ブランド84デザイン
 * 価格はJPY税込参考価格（1本）
 */
export const rings: Ring[] = [
  {
    slug: 'cherluv-campanule',
    brandSlug: 'cher-luv',
    nameEn: 'CAMPANULE',
    nameJa: 'カンパニュラ',
    nameZh: '卡帕努萊',
    category: 'marriage',
    conceptJa: '花言葉「誠実」',
    conceptZh: '花語「誠實」',
    descJa: 'ミル打ちを施したアンティーク調の細身リング。誠実さを象徴するカンパニュラの名を持つ。',
    descZh: '古典風格的細身戒指，以誠實為象徵的花語命名。',
    priceJPY: 97000,
    priceHighJPY: 187000,
    imageUrl: '/images/rings/cherluv-campanule.jpg',
    originalUrl: 'https://www.cher-luv.com/marriage/ma_campanule/',
    materials: ['Pt950', 'K18YG', 'K18PG'],
    featured: true,
  },
  {
    slug: 'cherluv-marguerite',
    brandSlug: 'cher-luv',
    nameEn: 'MARGUERITE',
    nameJa: 'マーガレット',
    nameZh: '瑪格麗特',
    category: 'marriage',
    conceptJa: '花言葉「真実の愛」',
    conceptZh: '花語「真實的愛」',
    descJa: 'ミル打ちを施したアンティーク調の結婚指輪。真実の愛を象徴するマーガレット。',
    descZh: '象徵真實之愛的古典風格婚戒。',
    priceJPY: 92000,
    priceHighJPY: 168000,
    imageUrl: '/images/rings/cherluv-marguerite.jpg',
    originalUrl: 'https://www.cher-luv.com/marriage/ma_marguerite/',
    materials: ['Pt950', 'K18YG', 'K18PG'],
    featured: false,
  },
  {
    slug: 'cherluv-ajuga',
    brandSlug: 'cher-luv',
    nameEn: 'AJUGA',
    nameJa: 'アジュガ',
    nameZh: '阿茹加',
    category: 'marriage',
    conceptJa: '花言葉「強く結ばれる」',
    conceptZh: '花語「緊密相連」',
    descJa: 'ミル打ちを施したアンティーク調。強い絆を象徴するアジュガ。',
    descZh: '象徵強烈羈絆的古典風格婚戒。',
    priceJPY: 130000,
    priceHighJPY: 275000,
    imageUrl: '/images/rings/cherluv-ajuga.jpg',
    originalUrl: 'https://www.cher-luv.com/marriage/ma_ajuga/',
    materials: ['Pt950', 'K18YG', 'K18PG'],
    featured: false,
  },
  {
    slug: 'cherluv-geranium',
    brandSlug: 'cher-luv',
    nameEn: 'GERANIUM',
    nameJa: 'ゼラニューム',
    nameZh: '天竺葵',
    category: 'marriage',
    conceptJa: '花言葉「無償の愛」',
    conceptZh: '花語「無私的愛」',
    descJa: '無償の愛を象徴するゼラニューム。ミル打ちの繊細な装飾が美しい。',
    descZh: '象徵無私之愛，細膩米粒紋裝飾的婚戒。',
    priceJPY: 138000,
    priceHighJPY: 272000,
    imageUrl: '/images/rings/cherluv-geranium.jpg',
    originalUrl: 'https://www.cher-luv.com/marriage/ma_geranium/',
    materials: ['Pt950', 'K18YG', 'K18PG'],
    featured: false,
  },
  {
    slug: 'cherluv-gardenia',
    brandSlug: 'cher-luv',
    nameEn: 'GARDENIA',
    nameJa: 'ガーデニア',
    nameZh: '梔子花',
    category: 'marriage',
    conceptJa: '花言葉「とても幸せです」',
    conceptZh: '花語「非常幸福」',
    descJa: '幸せを象徴するガーデニア。白い花のような清楚さを持つ。',
    descZh: '象徵幸福的梔子花，如白花般純潔典雅。',
    priceJPY: 125000,
    priceHighJPY: 255000,
    imageUrl: '/images/rings/cherluv-gardenia.jpg',
    originalUrl: 'https://www.cher-luv.com/marriage/ma_gardenia/',
    materials: ['Pt950', 'K18YG', 'K18PG'],
    featured: false,
  },
  {
    slug: 'cherluv-ivy',
    brandSlug: 'cher-luv',
    nameEn: 'IVY',
    nameJa: 'アイビー',
    nameZh: '常春藤',
    category: 'marriage',
    conceptJa: '花言葉「永遠の愛」',
    conceptZh: '花語「永恆的愛」',
    descJa: '永遠の愛を象徴するアイビー。つたが絡むような繊細な彫刻が特徴。',
    descZh: '象徵永恆之愛，如藤蔓般精緻雕刻的婚戒。',
    priceJPY: 125000,
    priceHighJPY: 295000,
    imageUrl: '/images/rings/cherluv-ivy.jpg',
    originalUrl: 'https://www.cher-luv.com/marriage/ma_ivy/',
    materials: ['Pt950', 'K18YG', 'K18PG'],
    featured: false,
  },
  {
    slug: 'cherluv-lily',
    brandSlug: 'cher-luv',
    nameEn: 'LILY',
    nameJa: 'リリー',
    nameZh: '百合',
    category: 'marriage',
    conceptJa: '花言葉「純潔」',
    conceptZh: '花語「純潔」',
    descJa: '純潔を象徴するリリー。すっきりとした細身のデザイン。',
    descZh: '象徵純潔的百合，線條簡潔的細身婚戒。',
    priceJPY: 126000,
    priceHighJPY: 282000,
    imageUrl: '/images/rings/cherluv-lily.jpg',
    originalUrl: 'https://www.cher-luv.com/marriage/ma_lily/',
    materials: ['Pt950', 'K18YG', 'K18PG'],
    featured: false,
  },
  {
    slug: 'cherluv-begonia',
    brandSlug: 'cher-luv',
    nameEn: 'BEGONIA',
    nameJa: 'ベゴニア',
    nameZh: '秋海棠',
    category: 'marriage',
    conceptJa: '花言葉「つり合いが良い」',
    conceptZh: '花語「天造地設」',
    descJa: 'つり合いの良さを象徴するベゴニア。ふたりの調和を表現した。',
    descZh: '象徵天造地設的秋海棠，表達兩人之間的和諧。',
    priceJPY: 167000,
    priceHighJPY: 343000,
    imageUrl: '/images/rings/cherluv-begonia.jpg',
    originalUrl: 'https://www.cher-luv.com/marriage/ma_begonia/',
    materials: ['Pt950', 'K18YG', 'K18PG'],
    featured: false,
  },
  {
    slug: 'cherluv-ranunculus',
    brandSlug: 'cher-luv',
    nameEn: 'RANUNCULUS',
    nameJa: 'ラナンキュラス',
    nameZh: '花毛茛',
    category: 'marriage',
    conceptJa: '花言葉「あなたは魅力的」',
    conceptZh: '花語「你魅力十足」',
    descJa: '魅力を象徴するラナンキュラス。豪華な花弁を思わせる重厚なデザイン。',
    descZh: '象徵魅力的花毛茛，如豐盛花瓣般華麗的設計。',
    priceJPY: 167000,
    priceHighJPY: 392000,
    imageUrl: '/images/rings/cherluv-ranunculus.jpg',
    originalUrl: 'https://www.cher-luv.com/marriage/ma_ranunculus/',
    materials: ['Pt950', 'K18YG', 'K18PG'],
    featured: false,
  },
  {
    slug: 'cherluv-muguet',
    brandSlug: 'cher-luv',
    nameEn: 'MUGUET',
    nameJa: 'ミュゲ',
    nameZh: '鈴蘭',
    category: 'marriage',
    conceptJa: '花言葉「幸福」',
    conceptZh: '花語「幸福」',
    descJa: '幸福を象徴するミュゲ（スズラン）。小さな花が連なるような繊細な彫刻。',
    descZh: '象徵幸福的鈴蘭，如小花連綿般細膩的雕刻。',
    priceJPY: 155000,
    priceHighJPY: 285000,
    imageUrl: '/images/rings/cherluv-muguet.jpg',
    originalUrl: 'https://www.cher-luv.com/marriage/ma_muguet/',
    materials: ['Pt950', 'K18YG', 'K18PG'],
    featured: false,
  },
  {
    slug: 'cherluv-matthiola',
    brandSlug: 'cher-luv',
    nameEn: 'MATTHIOLA',
    nameJa: 'マッティオラ',
    nameZh: '紫羅蘭',
    category: 'marriage',
    conceptJa: '花言葉「愛の絆」',
    conceptZh: '花語「愛的羈絆」',
    descJa: '愛の絆を象徴するマッティオラ。上品で落ち着いた雰囲気のデザイン。',
    descZh: '象徵愛的羈絆的紫羅蘭，優雅沉穩的設計風格。',
    priceJPY: 125000,
    priceHighJPY: 310000,
    imageUrl: '/images/rings/cherluv-matthiola.jpg',
    originalUrl: 'https://www.cher-luv.com/marriage/ma_matthiola/',
    materials: ['Pt950', 'K18YG', 'K18PG'],
    featured: false,
  },
  {
    slug: 'amour-azalea',
    brandSlug: 'amour-amulette',
    nameEn: 'AZALEA',
    nameJa: 'アザレア',
    nameZh: '阿扎萊亞',
    category: 'marriage',
    conceptJa: 'フランス語で「アザレア（花の名）」',
    conceptZh: '法語「杜鵑花」',
    descJa: 'ダイヤモンドを含む完成価格。全国60の正規取扱店でご試着いただけます。',
    descZh: '含鑽石的完整價格。可於全國60家正規經銷商試戴。',
    priceJPY: 265000,
    imageUrl: '/images/rings/amour-azalea.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/azalea/',
    materials: ['Pt900', 'Pt900コンビ', 'K18'],
    featured: true,
  },
  {
    slug: 'amour-miel',
    brandSlug: 'amour-amulette',
    nameEn: 'MIEL',
    nameJa: 'ミエル',
    nameZh: '蜂蜜',
    category: 'marriage',
    conceptJa: 'フランス語で「蜂蜜」',
    conceptZh: '法語「蜂蜜」',
    descJa: '蜂蜜のような甘さと温かみを表現。ダイヤモンドを含む完成価格。',
    descZh: '如蜂蜜般甜蜜溫暖的設計，含鑽石的完整價格。',
    priceJPY: 203000,
    imageUrl: '/images/rings/amour-miel.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/miel/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-bonheur',
    brandSlug: 'amour-amulette',
    nameEn: 'BONHEUR',
    nameJa: 'ボヌール',
    nameZh: '幸福',
    category: 'marriage',
    conceptJa: 'フランス語で「幸福」',
    conceptZh: '法語「幸福」',
    descJa: '幸福を意味するフランス語。ダイヤモンドを含む完成価格。',
    descZh: '法語「幸福」之意，含鑽石的完整價格。',
    priceJPY: 174000,
    imageUrl: '/images/rings/amour-bonheur.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/bonheur/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-chouchou',
    brandSlug: 'amour-amulette',
    nameEn: 'CHOU CHOU',
    nameJa: 'シュシュ',
    nameZh: '最愛',
    category: 'marriage',
    conceptJa: 'フランス語で「お気に入り、いとしい人」',
    conceptZh: '法語「最愛的人」',
    descJa: '「いとしい人」を意味する言葉を冠したリング。ダイヤモンドを含む完成価格。',
    descZh: '以「最愛的人」命名的婚戒，含鑽石的完整價格。',
    priceJPY: 205000,
    imageUrl: '/images/rings/amour-chouchou.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/chouchou/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-lumiere',
    brandSlug: 'amour-amulette',
    nameEn: 'LUMIERE',
    nameJa: 'ルミエール',
    nameZh: '光',
    category: 'marriage',
    conceptJa: 'フランス語で「光」',
    conceptZh: '法語「光」',
    descJa: '光を意味する名前。ダイヤモンドが放つ輝きを最大限に引き出すデザイン。',
    descZh: '以「光」命名，最大化展現鑽石光芒的設計。',
    priceJPY: 225000,
    imageUrl: '/images/rings/amour-lumiere.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/lumiere/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-attache',
    brandSlug: 'amour-amulette',
    nameEn: 'ATTACHE',
    nameJa: 'アターシュ',
    nameZh: '結繫',
    category: 'marriage',
    conceptJa: 'フランス語で「結びつける」',
    conceptZh: '法語「緊緊相連」',
    descJa: '「結びつける」を意味する名前。ふたりの絆を永遠に結ぶ。',
    descZh: '以「緊緊相連」命名，永遠牽繫兩人的羈絆。',
    priceJPY: 158000,
    imageUrl: '/images/rings/amour-attache.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/attache/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-monbijou',
    brandSlug: 'amour-amulette',
    nameEn: 'MON BIJOU',
    nameJa: 'モンビジュー',
    nameZh: '我的珠寶',
    category: 'marriage',
    conceptJa: 'フランス語で「わたしの宝石」',
    conceptZh: '法語「我的珠寶」',
    descJa: '「わたしの宝石」を意味する名前。存在感ある華やかなデザイン。',
    descZh: '以「我的珠寶」命名，華麗有存在感的設計。',
    priceJPY: 270000,
    imageUrl: '/images/rings/amour-monbijou.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/monbijou/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-millemercis',
    brandSlug: 'amour-amulette',
    nameEn: 'MILLE MERCIS',
    nameJa: 'ミルメルシー',
    nameZh: '千萬感謝',
    category: 'marriage',
    conceptJa: 'フランス語で「千の感謝」',
    conceptZh: '法語「千萬感謝」',
    descJa: '「千の感謝」を意味する。感謝と愛を込めたシンプルなデザイン。',
    descZh: '以「千萬感謝」命名，融入感謝與愛的簡約設計。',
    priceJPY: 148000,
    imageUrl: '/images/rings/amour-millemercis.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/millemercis/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-infinite',
    brandSlug: 'amour-amulette',
    nameEn: 'INFINITE',
    nameJa: 'アンフィニテ',
    nameZh: '無限',
    category: 'marriage',
    conceptJa: 'フランス語で「無限」',
    conceptZh: '法語「無限」',
    descJa: '「無限」を意味する名前。永遠に続く愛を象徴するデザイン。',
    descZh: '以「無限」命名，象徵永無止境之愛的設計。',
    priceJPY: 188000,
    imageUrl: '/images/rings/amour-infinite.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/infinite/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-calmer',
    brandSlug: 'amour-amulette',
    nameEn: 'CALMER',
    nameJa: 'カルメ',
    nameZh: '平靜',
    category: 'marriage',
    conceptJa: 'フランス語で「静める、和らげる」',
    conceptZh: '法語「平靜、舒緩」',
    descJa: '「静める」を意味する名前。穏やかな日常に寄り添うシンプルなリング。',
    descZh: '以「平靜」命名，陪伴平靜日常的簡約婚戒。',
    priceJPY: 125000,
    imageUrl: '/images/rings/amour-calmer.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/calmer/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-soleil',
    brandSlug: 'amour-amulette',
    nameEn: 'SOLEIL',
    nameJa: 'ソレイユ',
    nameZh: '太陽',
    category: 'marriage',
    conceptJa: 'フランス語で「太陽」',
    conceptZh: '法語「太陽」',
    descJa: '「太陽」を意味する名前。明るく温かな光を放つデザイン。',
    descZh: '以「太陽」命名，散發明亮溫暖光芒的設計。',
    priceJPY: 195000,
    imageUrl: '/images/rings/amour-soleil.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/soleil/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-fleur',
    brandSlug: 'amour-amulette',
    nameEn: 'FLEUR',
    nameJa: 'フルール',
    nameZh: '花',
    category: 'marriage',
    conceptJa: 'フランス語で「花」',
    conceptZh: '法語「花」',
    descJa: '「花」を意味する名前。花のような優雅さと愛らしさを持つデザイン。',
    descZh: '以「花」命名，如花朵般優雅可愛的設計。',
    priceJPY: 195000,
    imageUrl: '/images/rings/amour-fleur.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/fleur/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-iris',
    brandSlug: 'amour-amulette',
    nameEn: 'IRIS',
    nameJa: 'アイリス',
    nameZh: '鳶尾花',
    category: 'marriage',
    conceptJa: 'フランス語で「あやめ／虹の女神」',
    conceptZh: '法語「鳶尾花／彩虹女神」',
    descJa: '虹の女神の名を持つアイリス。色彩豊かな輝きをダイヤモンドで表現。',
    descZh: '以彩虹女神命名，以鑽石展現豐富光彩的設計。',
    priceJPY: 170000,
    imageUrl: '/images/rings/amour-iris.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/iris/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-cherir',
    brandSlug: 'amour-amulette',
    nameEn: 'CHERIR',
    nameJa: 'シェリー',
    nameZh: '珍愛',
    category: 'marriage',
    conceptJa: 'フランス語で「慈しむ、大切にする」',
    conceptZh: '法語「珍愛、呵護」',
    descJa: '「大切にする」を意味する名前。いつまでも大切にしたいと思える上質なリング。',
    descZh: '以「珍愛」命名，讓人想永遠珍惜的高品質婚戒。',
    priceJPY: 190000,
    imageUrl: '/images/rings/amour-cherir.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/cherir/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'amour-bonnequalite',
    brandSlug: 'amour-amulette',
    nameEn: 'BONNE QUALITE',
    nameJa: 'ボンヌカリテ',
    nameZh: '良質',
    category: 'marriage',
    conceptJa: 'フランス語で「良質」',
    conceptZh: '法語「優良品質」',
    descJa: '「良質」を意味する名前。素材と職人技へのこだわりを体現したリング。',
    descZh: '以「優良品質」命名，體現對素材和工藝極致追求的婚戒。',
    priceJPY: 190000,
    imageUrl: '/images/rings/amour-bonnequalite.jpg',
    originalUrl: 'https://amour-amulet.com/marriage/bonnequalite/',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'neuspur-flugel',
    brandSlug: 'neuspur', // ※ノイシュプールは独立ブランドのため要調整
    nameEn: 'Flügel',
    nameJa: 'フリューゲル',
    nameZh: '翅膀',
    category: 'engagement',
    conceptJa: '「翼」ふたりの未来へ、羽ばたくように',
    conceptZh: '「翅膀」如同展翅，飛向兩人的未來',
    descJa: '槌目の鎚の痕が残る、フルオーダー感覚の婚約指輪。PT900・K18対応。',
    descZh: '保留槌紋手感的訂婚戒指，如同全訂製的感覺。',
    priceJPY: 231000,
    imageUrl: '/images/rings/neuspur-flugel.jpg',
    originalUrl: 'https://neuspur.jp/ring-flugel.html',
    materials: ['Pt900', 'K18YG', 'K18WG'],
    featured: true,
  },
  {
    slug: 'neuspur-ehren',
    brandSlug: 'neuspur',
    nameEn: 'Ehren',
    nameJa: 'エーレン',
    nameZh: '榮耀',
    category: 'engagement',
    conceptJa: 'ドイツ語で「名誉・称える」',
    conceptZh: '德語「榮耀」',
    descJa: '槌目を施した、ふたつとない婚約指輪。¥187,000〜。',
    descZh: '每一枚都是獨一無二的槌紋訂婚戒指。',
    priceJPY: 187000,
    imageUrl: '/images/rings/neuspur-ehren.jpg',
    originalUrl: 'https://neuspur.jp/ring-ehren.html',
    materials: ['Pt900', 'K18YG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'neuspur-glanz',
    brandSlug: 'neuspur',
    nameEn: 'Glanz',
    nameJa: 'グランツ',
    nameZh: '光輝',
    category: 'engagement',
    conceptJa: 'ドイツ語で「輝き・光彩」',
    conceptZh: '德語「光輝」',
    descJa: '職人がフリーハンドで刻む槌目の婚約指輪。¥198,000〜。',
    descZh: '職人徒手刻製槌紋的訂婚戒指。',
    priceJPY: 198000,
    imageUrl: '/images/rings/neuspur-glanz.jpg',
    originalUrl: 'https://neuspur.jp/ring-glanz.html',
    materials: ['Pt900', 'K18YG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'neuspur-licht',
    brandSlug: 'neuspur',
    nameEn: 'Licht',
    nameJa: 'リヒト',
    nameZh: '光',
    category: 'engagement',
    conceptJa: 'ドイツ語で「光」',
    conceptZh: '德語「光」',
    descJa: '光のように輝く槌目の婚約指輪。¥225,500〜。',
    descZh: '如光般閃耀的槌紋訂婚戒指。',
    priceJPY: 225500,
    imageUrl: '/images/rings/neuspur-licht.jpg',
    originalUrl: 'https://neuspur.jp/ring-licht.html',
    materials: ['Pt900', 'K18YG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'neuspur-liebe',
    brandSlug: 'neuspur',
    nameEn: 'Liebe',
    nameJa: 'リーベ',
    nameZh: '愛',
    category: 'engagement',
    conceptJa: 'ドイツ語で「愛」',
    conceptZh: '德語「愛」',
    descJa: '愛を意味するドイツ語の名を持つ婚約指輪。¥209,000〜。',
    descZh: '以德語「愛」命名的訂婚戒指。',
    priceJPY: 209000,
    imageUrl: '/images/rings/neuspur-liebe.jpg',
    originalUrl: 'https://neuspur.jp/ring-liebe.html',
    materials: ['Pt900', 'K18YG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'neuspur-hanna',
    brandSlug: 'neuspur',
    nameEn: 'Hanna',
    nameJa: 'ハンナ',
    nameZh: '恩典',
    category: 'engagement',
    conceptJa: 'ヘブライ語で「神の恵み」',
    conceptZh: '希伯來語「神的恩典」',
    descJa: '神の恵みを意味する名を持つ婚約指輪。¥225,000〜。',
    descZh: '以「神的恩典」命名的訂婚戒指。',
    priceJPY: 225000,
    imageUrl: '/images/rings/neuspur-hanna.jpg',
    originalUrl: 'https://neuspur.jp/ring-hanna.html',
    materials: ['Pt900', 'K18YG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'neuspur-mogen',
    brandSlug: 'neuspur',
    nameEn: 'Mogen',
    nameJa: 'モーゲン',
    nameZh: '明天',
    category: 'engagement',
    conceptJa: 'ドイツ語で「明日・朝」',
    conceptZh: '德語「明天・早晨」',
    descJa: '明日への希望を表す名を持つ婚約指輪。¥225,500〜。',
    descZh: '以「明天」命名，象徵對未來希望的訂婚戒指。',
    priceJPY: 225500,
    imageUrl: 'https://neuspur.jp/img/rings/mogen.jpg',
    originalUrl: 'https://neuspur.jp/ring-mogen.html',
    materials: ['Pt900', 'K18YG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'neuspur-ilka',
    brandSlug: 'neuspur',
    nameEn: 'Ilka',
    nameJa: 'イルカ',
    nameZh: '意爾卡',
    category: 'engagement',
    conceptJa: 'スラブ系の名前「勤勉な人」',
    conceptZh: '斯拉夫名「勤奮之人」',
    descJa: '勤勉さを意味する名を持つ婚約指輪。¥167,200〜。',
    descZh: '以「勤奮」命名的訂婚戒指。',
    priceJPY: 167200,
    imageUrl: '/images/rings/neuspur-ilka.jpg',
    originalUrl: 'https://neuspur.jp/ring-ilka.html',
    materials: ['Pt900', 'K18YG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'neuspur-charmant',
    brandSlug: 'neuspur',
    nameEn: 'Charmant',
    nameJa: 'シャルマント',
    nameZh: '迷人',
    category: 'engagement',
    conceptJa: 'フランス語で「魅力的」',
    conceptZh: '法語「迷人的」',
    descJa: '魅力的を意味するフランス語の名を持つ婚約指輪。¥187,000〜。',
    descZh: '以法語「迷人」命名的訂婚戒指。',
    priceJPY: 187000,
    imageUrl: 'https://neuspur.jp/img/rings/charmant.jpg',
    originalUrl: 'https://neuspur.jp/ring-charmant.html',
    materials: ['Pt900', 'K18YG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'neuspur-eid',
    brandSlug: 'neuspur',
    nameEn: 'Eid',
    nameJa: 'アイト',
    nameZh: '誓言',
    category: 'engagement',
    conceptJa: 'アラビア語で「祝祭・誓い」',
    conceptZh: '阿拉伯語「節日・誓言」',
    descJa: '誓いを意味するアラビア語の名を持つ婚約指輪。¥198,000〜。',
    descZh: '以阿拉伯語「誓言」命名的訂婚戒指。',
    priceJPY: 198000,
    imageUrl: 'https://neuspur.jp/img/rings/eid.jpg',
    originalUrl: 'https://neuspur.jp/ring-eid.html',
    materials: ['Pt900', 'K18YG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'ironoha-bouquet',
    brandSlug: 'ironoha',
    nameEn: 'BOUQUET',
    nameJa: 'ブーケ',
    nameZh: '花束',
    category: 'marriage',
    conceptJa: '花束のような華やかさ',
    conceptZh: '如花束般的絢麗',
    descJa: '和モダンの美意識が宿る、花束を思わせる華やかな結婚指輪。日本の伝統美を現代に昇華したデザイン。',
    descZh: '融入和風現代美學，如花束般華麗的結婚戒指。將日本傳統美昇華為現代設計。',
    priceJPY: 227000,
    priceHighJPY: 352000,
    imageUrl: '/images/rings/ironoha-bouquet.jpg',
    originalUrl: 'https://ironoha.jp/ring/mar-bouquet.html',
    materials: ['Pt950', 'K18YG', 'K18PG', 'K18WG'],
    featured: true,
  },
  {
    slug: 'ironoha-eternal',
    brandSlug: 'ironoha',
    nameEn: 'ETERNAL',
    nameJa: 'エターナル',
    nameZh: '永恆',
    category: 'marriage',
    conceptJa: '永遠に続くふたりの時間',
    conceptZh: '永恆延續的兩人時光',
    descJa: '永遠を意味するエターナル。時を超えて輝き続ける和モダンの結婚指輪。',
    descZh: '以「永恆」為名，超越時間持續閃耀的和風現代婚戒。',
    priceJPY: 178000,
    priceHighJPY: 302000,
    imageUrl: '/images/rings/ironoha-eternal.jpg',
    originalUrl: 'https://ironoha.jp/ring/mar-eternal.html',
    materials: ['Pt950', 'K18YG', 'K18PG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'ironoha-fostering',
    brandSlug: 'ironoha',
    nameEn: 'FOSTERING',
    nameJa: 'フォスタリング',
    nameZh: '培育',
    category: 'marriage',
    conceptJa: '育む愛の形',
    conceptZh: '培育愛的形狀',
    descJa: '育む愛のかたちを表現した結婚指輪。ふたりの絆が年を重ねるごとに深まることを願って。',
    descZh: '表達培育之愛形狀的結婚戒指，祝願兩人的羈絆隨歲月加深。',
    priceJPY: 189000,
    priceHighJPY: 311000,
    imageUrl: '/images/rings/ironoha-fostering.jpg',
    originalUrl: 'https://ironoha.jp/ring/mar-fostering.html',
    materials: ['Pt950', 'K18YG', 'K18PG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'ironoha-harmony',
    brandSlug: 'ironoha',
    nameEn: 'HARMONY',
    nameJa: 'ハーモニー',
    nameZh: '和諧',
    category: 'marriage',
    conceptJa: 'ふたりの調和',
    conceptZh: '兩人的和諧',
    descJa: '調和を意味するハーモニー。異なる個性を持つふたりが共鳴し合うデザイン。',
    descZh: '以「和諧」為名，兩個不同個性相互共鳴的設計。',
    priceJPY: 203000,
    priceHighJPY: 300000,
    imageUrl: '/images/rings/ironoha-harmony.jpg',
    originalUrl: 'https://ironoha.jp/ring/mar-harmony.html',
    materials: ['Pt950', 'K18YG', 'K18PG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'ironoha-illuminate',
    brandSlug: 'ironoha',
    nameEn: 'ILLUMINATE',
    nameJa: 'イルミネイト',
    nameZh: '光照',
    category: 'marriage',
    conceptJa: '光のように照らす愛',
    conceptZh: '如光照耀的愛',
    descJa: '光のように互いを照らし合うふたりの愛を表現。和の意匠が光の動きを取り込んだデザイン。',
    descZh: '表現如光互相照耀的兩人之愛，和風意匠融入光之動感的設計。',
    priceJPY: 210000,
    priceHighJPY: 350000,
    imageUrl: '/images/rings/ironoha-illuminate.jpg',
    originalUrl: 'https://ironoha.jp/ring/mar-illuminate.html',
    materials: ['Pt950', 'K18YG', 'K18PG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'ironoha-happiness',
    brandSlug: 'ironoha',
    nameEn: 'HAPPINESS',
    nameJa: 'ハピネス',
    nameZh: '幸福',
    category: 'marriage',
    conceptJa: 'ふたりの幸せのかたち',
    conceptZh: '兩人幸福的形狀',
    descJa: '幸福そのものを指輪に込めた。和モダンの繊細な造形が、毎日の幸せを手元に宿す。',
    descZh: '將幸福本身融入戒指，和風現代細膩的造型讓幸福每天伴隨左右。',
    priceJPY: 218000,
    priceHighJPY: 322000,
    imageUrl: '/images/rings/ironoha-happiness.jpg',
    originalUrl: 'https://ironoha.jp/ring/mar-happiness.html',
    materials: ['Pt950', 'K18YG', 'K18PG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'ironoha-promise',
    brandSlug: 'ironoha',
    nameEn: 'PROMISE',
    nameJa: 'プロミス',
    nameZh: '約定',
    category: 'marriage',
    conceptJa: '変わらない約束を指輪に',
    conceptZh: '將不變的約定刻入戒指',
    descJa: '変わらない約束を和の美意識で表現した結婚指輪。シンプルでありながら深みを持つデザイン。',
    descZh: '以和風美學表達不變約定的結婚戒指，簡約而富有深度的設計。',
    priceJPY: 205000,
    priceHighJPY: 325000,
    imageUrl: '/images/rings/ironoha-promise.jpg',
    originalUrl: 'https://ironoha.jp/ring/mar-promise.html',
    materials: ['Pt950', 'K18YG', 'K18PG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'ironoha-sunny',
    brandSlug: 'ironoha',
    nameEn: 'SUNNY',
    nameJa: 'サニー',
    nameZh: '陽光',
    category: 'marriage',
    conceptJa: '晴れの日のような明るさ',
    conceptZh: '如晴天般的明朗',
    descJa: '晴れの日の陽光のように、ふたりの未来を明るく照らす結婚指輪。',
    descZh: '如晴天陽光般，照亮兩人未來的結婚戒指。',
    priceJPY: 210000,
    priceHighJPY: 300000,
    imageUrl: '/images/rings/ironoha-sunny.jpg',
    originalUrl: 'https://ironoha.jp/ring/mar-sunny.html',
    materials: ['Pt950', 'K18YG', 'K18PG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'ironoha-twinkle',
    brandSlug: 'ironoha',
    nameEn: 'TWINKLE',
    nameJa: 'トゥインクル',
    nameZh: '閃爍',
    category: 'marriage',
    conceptJa: '星のようにきらめく婚約指輪',
    conceptZh: '如星光般閃耀的訂婚戒指',
    descJa: '星のようにきらめく、和モダンの最高峰コレクション。ダイヤモンドと職人技が融合した一品。',
    descZh: '如星光閃耀的和風現代頂級系列，鑽石與職人技藝完美融合的珍品。',
    priceJPY: 368000,
    priceHighJPY: 432000,
    imageUrl: '/images/rings/ironoha-twinkle.jpg',
    originalUrl: 'https://ironoha.jp/ring/mar-twinkle.html',
    materials: ['Pt950', 'K18YG', 'K18PG', 'K18WG'],
    featured: false,
  },
  {
    slug: 'ankhore-storia',
    brandSlug: 'anc-coeur',
    nameEn: 'STORIA',
    nameJa: 'ストーリア',
    nameZh: '故事',
    category: 'marriage',
    conceptJa: '「この恋の物語」',
    conceptZh: '「這段愛情的故事」',
    descJa: 'イタリア語で「物語」。ふたりだけの恋の物語を、このリングに刻んで。Pt900・K18・K10対応。',
    descZh: '義大利語「故事」之意，將兩人專屬的愛情故事刻入戒指。',
    priceJPY: 115000,
    priceHighJPY: 184000,
    imageUrl: '/images/rings/ankhore-storia.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: true,
  },
  {
    slug: 'ankhore-speccio',
    brandSlug: 'anc-coeur',
    nameEn: 'SPECCIO',
    nameJa: 'スペッキオ',
    nameZh: '鏡子',
    category: 'marriage',
    conceptJa: '「同じ気持ちで」',
    conceptZh: '「相同的心意」',
    descJa: 'イタリア語で「鏡」。互いを映し合う二人の気持ちを表現したペアリング。',
    descZh: '義大利語「鏡子」之意，表達兩人互相映照心意的對戒。',
    priceJPY: 125000,
    priceHighJPY: 174000,
    imageUrl: '/images/rings/ankhore-speccio.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: false,
  },
  {
    slug: 'ankhore-voce',
    brandSlug: 'anc-coeur',
    nameEn: 'VOCE',
    nameJa: 'ヴォーチェ',
    nameZh: '聲音',
    category: 'marriage',
    conceptJa: '「伝わる気持ち」',
    conceptZh: '「傳遞的心意」',
    descJa: 'イタリア語で「声」。言葉にならない気持ちを、指輪の形で伝える。',
    descZh: '義大利語「聲音」之意，以戒指的形式傳遞無法言喻的心意。',
    priceJPY: 131000,
    priceHighJPY: 189000,
    imageUrl: '/images/rings/ankhore-voce.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: false,
  },
  {
    slug: 'ankhore-palma',
    brandSlug: 'anc-coeur',
    nameEn: 'PALMA',
    nameJa: 'パルマ',
    nameZh: '手掌',
    category: 'marriage',
    conceptJa: '「繋がる想い」',
    conceptZh: '「緊繫的思念」',
    descJa: 'イタリア語で「手のひら」。手を繋ぐように、想いが繋がるリング。',
    descZh: '義大利語「手掌」之意，如牽手般讓思念相連的戒指。',
    priceJPY: 121000,
    priceHighJPY: 179000,
    imageUrl: '/images/rings/ankhore-palma.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: false,
  },
  {
    slug: 'ankhore-cara',
    brandSlug: 'anc-coeur',
    nameEn: 'CARA',
    nameJa: 'カーラ',
    nameZh: '親愛',
    category: 'marriage',
    conceptJa: '「愛しい君へ」',
    conceptZh: '「獻給摯愛的你」',
    descJa: 'イタリア語で「愛しい人」。大切な君への気持ちを込めたペアリング。',
    descZh: '義大利語「摯愛之人」之意，融入對你深切情意的對戒。',
    priceJPY: 120000,
    priceHighJPY: 176000,
    imageUrl: '/images/rings/ankhore-cara.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: false,
  },
  {
    slug: 'ankhore-vita',
    brandSlug: 'anc-coeur',
    nameEn: 'VITA',
    nameJa: 'ヴィータ',
    nameZh: '生命',
    category: 'marriage',
    conceptJa: '「ふたりが交わす未来」',
    conceptZh: '「兩人共許的未來」',
    descJa: 'イタリア語で「生命・人生」。ふたりの人生を共に歩む誓いのリング。',
    descZh: '義大利語「生命」之意，共同走過人生旅途的誓約戒指。',
    priceJPY: 118000,
    priceHighJPY: 169000,
    imageUrl: '/images/rings/ankhore-vita.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: false,
  },
  {
    slug: 'ankhore-felice',
    brandSlug: 'anc-coeur',
    nameEn: 'FELICE',
    nameJa: 'フェリーチェ',
    nameZh: '幸福',
    category: 'marriage',
    conceptJa: '「あなたがくれた幸せ」',
    conceptZh: '「你給我的幸福」',
    descJa: 'イタリア語で「幸せ」。あなたとの出会いがくれた幸せを、このリングに。',
    descZh: '義大利語「幸福」之意，將與你相遇帶來的幸福融入這枚戒指。',
    priceJPY: 110000,
    priceHighJPY: 151000,
    imageUrl: '/images/rings/ankhore-felice.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: false,
  },
  {
    slug: 'ankhore-sperare',
    brandSlug: 'anc-coeur',
    nameEn: 'SPERARE',
    nameJa: 'スペラーレ',
    nameZh: '希望',
    category: 'marriage',
    conceptJa: '「願いはきっと叶う」',
    conceptZh: '「願望一定會實現」',
    descJa: 'イタリア語で「願う・望む」。ふたりの願いが叶うようにと祈りを込めたリング。',
    descZh: '義大利語「希望・祈願」之意，祈願兩人心願實現的戒指。',
    priceJPY: 118000,
    priceHighJPY: 176000,
    imageUrl: '/images/rings/ankhore-sperare.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: false,
  },
  {
    slug: 'ankhore-sinfonia',
    brandSlug: 'anc-coeur',
    nameEn: 'SINFONIA',
    nameJa: 'シンフォニア',
    nameZh: '交響曲',
    category: 'marriage',
    conceptJa: '「重なる想い」',
    conceptZh: '「交疊的思念」',
    descJa: 'イタリア語で「交響曲」。ふたりの気持ちが重なり合い、美しいハーモニーを奏でる。',
    descZh: '義大利語「交響曲」之意，兩人的心意交疊，奏出美麗和聲。',
    priceJPY: 141000,
    priceHighJPY: 210000,
    imageUrl: '/images/rings/ankhore-sinfonia.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: false,
  },
  {
    slug: 'ankhore-stella',
    brandSlug: 'anc-coeur',
    nameEn: 'STELLA',
    nameJa: 'ステラ',
    nameZh: '星',
    category: 'marriage',
    conceptJa: '「みつけてくれてありがとう」',
    conceptZh: '「謝謝你找到我」',
    descJa: 'イタリア語で「星」。星の数ほどある出会いの中で、みつけてくれたことへの感謝を込めて。',
    descZh: '義大利語「星」之意，在無數相遇中感謝你找到我的戒指。',
    priceJPY: 148000,
    priceHighJPY: 183000,
    imageUrl: '/images/rings/ankhore-stella.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: false,
  },
  {
    slug: 'ankhore-fossetta',
    brandSlug: 'anc-coeur',
    nameEn: 'FOSSETTA',
    nameJa: 'フォセッタ',
    nameZh: '酒窩',
    category: 'marriage',
    conceptJa: '「笑顔のしるし」',
    conceptZh: '「笑顏的印記」',
    descJa: 'イタリア語で「えくぼ」。笑顔のような温かさで包む、愛らしいペアリング。',
    descZh: '義大利語「酒窩」之意，如笑顏般溫暖包覆的可愛對戒。',
    priceJPY: 95000,
    priceHighJPY: 146000,
    imageUrl: '/images/rings/ankhore-fossetta.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: false,
  },
  {
    slug: 'ankhore-luce',
    brandSlug: 'anc-coeur',
    nameEn: 'LUCE',
    nameJa: 'ルーチェ',
    nameZh: '光',
    category: 'marriage',
    conceptJa: '「やさしい光に包まれて」',
    conceptZh: '「被柔和的光包圍」',
    descJa: 'イタリア語で「光」。柔らかな光に包まれるような、華やかさと上品さを兼ね備えたリング。',
    descZh: '義大利語「光」之意，如柔和光芒環繞，兼具華麗與優雅的戒指。',
    priceJPY: 220000,
    priceHighJPY: 246000,
    imageUrl: '/images/rings/ankhore-luce.jpg',
    originalUrl: 'https://www.ankhore.com/collection/',
    materials: ['Pt900', 'K18', 'K10'],
    featured: false,
  },
  {
    slug: 'baum-camellia',
    brandSlug: 'baum',
    nameEn: 'CAMELLIA',
    nameJa: 'カメリア',
    nameZh: '山茶花',
    category: 'marriage',
    conceptJa: '優しい木漏れ日に包まれた愛',
    conceptZh: '被柔和林間光影包圍的愛',
    descJa: 'バウムを象徴する木漏れ日モチーフ。カメリア（椿）の名を持つ、やわらかな曲線が美しい結婚指輪。',
    descZh: '象徵BAUM的林間光影主題。以山茶花命名，柔美曲線的結婚戒指。',
    priceJPY: 145000,
    priceHighJPY: 257000,
    imageUrl: 'https://baum-ring.com/img/collection/mar-camellia.jpg',
    originalUrl: 'https://baum-ring.com/collection-lineup.html#m1',
    materials: ['Pt900', 'K18'],
    featured: true,
  },
  {
    slug: 'baum-angellamp',
    brandSlug: 'baum',
    nameEn: 'ANGEL LAMP',
    nameJa: 'エンゼルランプ',
    nameZh: '天使燈',
    category: 'marriage',
    conceptJa: '幸せの始まり',
    conceptZh: '幸福的開始',
    descJa: '幸せの始まりを灯すエンゼルランプ。温かな光のように、ふたりの未来を照らす。',
    descZh: '點亮幸福開始的天使燈，如溫暖的光芒照耀兩人的未來。',
    priceJPY: 190000,
    priceHighJPY: 293000,
    imageUrl: 'https://baum-ring.com/img/collection/mar-crapemyrtle.jpg',
    originalUrl: 'https://baum-ring.com/collection-lineup.html#m2',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'baum-viburnum',
    brandSlug: 'baum',
    nameEn: 'VIBURNUM',
    nameJa: 'ビバーナム',
    nameZh: '莢蒾',
    category: 'marriage',
    conceptJa: '結ばれた愛のかたち',
    conceptZh: '相繫之愛的形狀',
    descJa: 'ビバーナム（スノーボール）の可憐な花が、ふたりの愛の絆を表現する。',
    descZh: '莢蒾（雪球花）嬌美的花朵，表達兩人愛的羈絆。',
    priceJPY: 180000,
    priceHighJPY: 290000,
    imageUrl: 'https://baum-ring.com/img/collection/mar-viburnum.jpg',
    originalUrl: 'https://baum-ring.com/collection-lineup.html#m3',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'baum-magnolia',
    brandSlug: 'baum',
    nameEn: 'MAGNOLIA',
    nameJa: 'マグノリア',
    nameZh: '木蘭',
    category: 'marriage',
    conceptJa: 'いつまでも変わらない二人でいよう',
    conceptZh: '讓我們永遠不變',
    descJa: 'マグノリア（モクレン）のように、変わらず美しいふたりの愛を表現したリング。',
    descZh: '如木蘭花般，表達永遠美麗不變的兩人之愛。',
    priceJPY: 138000,
    priceHighJPY: 260000,
    imageUrl: 'https://baum-ring.com/img/collection/mar-magnolia.jpg',
    originalUrl: 'https://baum-ring.com/collection-lineup.html#m4',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'baum-olive',
    brandSlug: 'baum',
    nameEn: 'OLIVE',
    nameJa: 'オリーブ',
    nameZh: '橄欖',
    category: 'marriage',
    conceptJa: '側に居られることの幸せ',
    conceptZh: '能在你身旁的幸福',
    descJa: '平和と実りを象徴するオリーブ。傍に居てくれることへの感謝を込めたリング。',
    descZh: '象徵和平與豐收的橄欖，融入感謝你陪伴在身旁的戒指。',
    priceJPY: 190000,
    priceHighJPY: 285000,
    imageUrl: 'https://baum-ring.com/img/collection/mar-olive.jpg',
    originalUrl: 'https://baum-ring.com/collection-lineup.html#m5',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'baum-pieris',
    brandSlug: 'baum',
    nameEn: 'PIERIS',
    nameJa: 'ピエリス',
    nameZh: '馬醉木',
    category: 'marriage',
    conceptJa: '終わらない物語をあなたと二人で',
    conceptZh: '與你共同譜寫永無止境的故事',
    descJa: '春に鈴なりの花を咲かせるピエリスのように、ふたりの物語は続いていく。',
    descZh: '如春日繁花盛開的馬醉木，兩人的故事將永遠延續。',
    priceJPY: 160000,
    priceHighJPY: 253000,
    imageUrl: 'https://baum-ring.com/img/collection/mar-pieris.jpg',
    originalUrl: 'https://baum-ring.com/collection-lineup.html#m6',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'baum-hanamizuki',
    brandSlug: 'baum',
    nameEn: 'HANAMIZUKI',
    nameJa: 'ハナミズキ',
    nameZh: '大花四照花',
    category: 'marriage',
    conceptJa: 'まっすぐなあなたへの想い',
    conceptZh: '對你直率的思念',
    descJa: '春の花ハナミズキのように、まっすぐに伸びるふたりの愛。シンプルで力強いデザイン。',
    descZh: '如春日大花四照花筆直生長，表達對你直率的愛。簡約有力的設計。',
    priceJPY: 150000,
    priceHighJPY: 213000,
    imageUrl: 'https://baum-ring.com/img/collection/mar-hanamizuki.jpg',
    originalUrl: 'https://baum-ring.com/collection-lineup.html#m7',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'promise-uandi',
    brandSlug: 'promise-ring',
    nameEn: 'U&I',
    nameJa: 'ユーアンドアイ',
    nameZh: '你與我',
    category: 'set',
    conceptJa: '「あなたとわたしの約束」',
    conceptZh: '「你與我的約定」',
    descJa: 'シンプルなフォルムに「あなたとわたし」の約束を込めたスタータコレクション。毎日つけ続けたくなる着け心地。',
    descZh: '以簡約造型融入「你與我」約定的入門系列，讓你每天都想佩戴。',
    priceJPY: 143000,
    imageUrl: 'https://promise-ring.jp/img/ring/uandi-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: true,
  },
  {
    slug: 'promise-love',
    brandSlug: 'promise-ring',
    nameEn: 'LOVE',
    nameJa: 'ラブ',
    nameZh: '愛',
    category: 'set',
    conceptJa: '「愛の約束」',
    conceptZh: '「愛的約定」',
    descJa: '愛そのものを名前に持つコレクション。ダイヤモンドが愛の輝きを添える。',
    descZh: '以「愛」本身命名的系列，鑽石為愛的光芒增添閃耀。',
    priceJPY: 163000,
    imageUrl: 'https://promise-ring.jp/img/ring/love-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'promise-joy',
    brandSlug: 'promise-ring',
    nameEn: 'JOY',
    nameJa: 'ジョイ',
    nameZh: '喜悅',
    category: 'set',
    conceptJa: '「喜びの約束」',
    conceptZh: '「喜悅的約定」',
    descJa: '喜びを分かち合うふたりへ。シンプルで清潔感あふれるデザイン。',
    descZh: '獻給共同分享喜悅的兩人，簡約清爽的設計。',
    priceJPY: 143000,
    imageUrl: 'https://promise-ring.jp/img/ring/joy-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'promise-smile',
    brandSlug: 'promise-ring',
    nameEn: 'SMILE',
    nameJa: 'スマイル',
    nameZh: '微笑',
    category: 'set',
    conceptJa: '「笑顔の約束」',
    conceptZh: '「微笑的約定」',
    descJa: '毎日笑顔でいられるように。温かみのあるデザインが手元を華やかに彩る。',
    descZh: '讓每天都能帶著微笑，溫暖的設計讓手部更加亮麗。',
    priceJPY: 155000,
    imageUrl: 'https://promise-ring.jp/img/ring/smile-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'promise-trust',
    brandSlug: 'promise-ring',
    nameEn: 'TRUST',
    nameJa: 'トラスト',
    nameZh: '信任',
    category: 'set',
    conceptJa: '「信頼の約束」',
    conceptZh: '「信任的約定」',
    descJa: '互いへの信頼を指輪に込めて。着け心地のよいシンプルな一本。',
    descZh: '將對彼此的信任融入戒指，舒適易戴的簡約款式。',
    priceJPY: 158000,
    imageUrl: 'https://promise-ring.jp/img/ring/trust-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'promise-passion',
    brandSlug: 'promise-ring',
    nameEn: 'PASSION',
    nameJa: 'パッション',
    nameZh: '熱情',
    category: 'set',
    conceptJa: '「情熱の約束」',
    conceptZh: '「熱情的約定」',
    descJa: '情熱を持ってふたりの未来へ。存在感のあるデザインで手元を彩る。',
    descZh: '懷著熱情邁向兩人的未來，存在感十足的設計點亮手部。',
    priceJPY: 158000,
    imageUrl: 'https://promise-ring.jp/img/ring/passion-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'promise-harmony',
    brandSlug: 'promise-ring',
    nameEn: 'HARMONY',
    nameJa: 'ハーモニー',
    nameZh: '和諧',
    category: 'set',
    conceptJa: '「調和の約束」',
    conceptZh: '「和諧的約定」',
    descJa: 'ふたりの調和を表現したハーモニー。男女どちらにも似合うバランスのいいデザイン。',
    descZh: '表達兩人和諧的系列，男女皆宜的均衡設計。',
    priceJPY: 147000,
    imageUrl: 'https://promise-ring.jp/img/ring/harmony-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'promise-eternal',
    brandSlug: 'promise-ring',
    nameEn: 'ETERNAL',
    nameJa: 'エターナル',
    nameZh: '永恆',
    category: 'set',
    conceptJa: '「永遠の約束」',
    conceptZh: '「永恆的約定」',
    descJa: '永遠を誓うエターナル。シンプルかつ飽きのこないデザインが長く愛用できる。',
    descZh: '誓言永恆的系列，簡約不過時的設計可以長久珍藏。',
    priceJPY: 146000,
    imageUrl: 'https://promise-ring.jp/img/ring/eternal-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'promise-star',
    brandSlug: 'promise-ring',
    nameEn: 'STAR',
    nameJa: 'スター',
    nameZh: '星',
    category: 'set',
    conceptJa: '「星の約束」',
    conceptZh: '「星的約定」',
    descJa: '星のように輝くふたりの約束。ダイヤモンドが夜空の星のようにきらめく。',
    descZh: '如星光閃耀的兩人約定，鑽石如夜空星辰般閃爍。',
    priceJPY: 146000,
    imageUrl: 'https://promise-ring.jp/img/ring/star-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'promise-happy',
    brandSlug: 'promise-ring',
    nameEn: 'HAPPY',
    nameJa: 'ハッピー',
    nameZh: '快樂',
    category: 'set',
    conceptJa: '「幸せの約束」',
    conceptZh: '「幸福的約定」',
    descJa: '幸せをかたちにしたハッピー。毎日が幸せであるようにとの願いを込めて。',
    descZh: '將幸福具體化的系列，寄託每天都能幸福的祝願。',
    priceJPY: 155000,
    imageUrl: 'https://promise-ring.jp/img/ring/happy-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'promise-emotion',
    brandSlug: 'promise-ring',
    nameEn: 'EMOTION',
    nameJa: 'エモーション',
    nameZh: '感動',
    category: 'set',
    conceptJa: '「感動の約束」',
    conceptZh: '「感動的約定」',
    descJa: '感動をふたりで分かち合う。ウェーブラインがリングに動きと表情を与える。',
    descZh: '與你共同分享感動，波浪線條為戒指帶來動感與表情。',
    priceJPY: 162000,
    imageUrl: 'https://promise-ring.jp/img/ring/emotion-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'promise-luminous',
    brandSlug: 'promise-ring',
    nameEn: 'LUMINOUS',
    nameJa: 'ルミナス',
    nameZh: '光輝',
    category: 'set',
    conceptJa: '「光り輝く約束」',
    conceptZh: '「光芒閃耀的約定」',
    descJa: '光り輝く未来への約束。パヴェダイヤが手元を豪華に彩るプレミアムコレクション。',
    descZh: '對光輝未來的約定，密鑲鑽石為手部增添華麗光彩的頂級系列。',
    priceJPY: 164000,
    imageUrl: 'https://promise-ring.jp/img/ring/luminous-set.jpg',
    originalUrl: 'https://promise-ring.jp/#rings',
    materials: ['Pt900', 'K18'],
    featured: false,
  },
  {
    slug: 'heartisland-ohana',
    brandSlug: 'heart-island',
    nameEn: 'Ohana',
    nameJa: 'オハナ',
    nameZh: '家族',
    category: 'marriage',
    conceptJa: 'ハワイ語で「家族」——生まれゆく新たな絆へ',
    conceptZh: '夏威夷語「家族」——邁向誕生的新羈絆',
    descJa: '職人が一本ずつフリーハンドで手彫りするハワイアンジュエリー。オハナはハワイ語で「家族」を意味し、ふたりが築く新しい家族への祝福を込めた彫りです。',
    descZh: '職人以徒手逐一手雕的夏威夷珠寶。Ohana在夏威夷語中意為「家族」，蘊含對兩人建立新家庭的祝福。',
    priceJPY: 170000,
    imageUrl: '/images/rings/heartisland-ohana.jpg',
    originalUrl: 'https://heartisland.jp/collection.html',
    materials: ['Pt900', 'K18WG', 'K18PG', 'K18YG', 'K10'],
    featured: true,
  },
  {
    slug: 'heartisland-tropical-scroll',
    brandSlug: 'heart-island',
    nameEn: 'Tropical Scroll',
    nameJa: 'トロピカルスクロール',
    nameZh: '熱帶卷草',
    category: 'marriage',
    conceptJa: '幸せを運ぶ波が、絶え間なくふたりを包む',
    conceptZh: '帶來幸福的浪潮，不斷包圍著兩人',
    descJa: 'ハワイの海を流れる波をモチーフに。幸せを運ぶ波が途切れることなくふたりを包み込む、エントリーコレクション。',
    descZh: '以夏威夷海洋的波浪為主題，帶來幸福的浪潮源源不斷地包圍兩人，入門系列。',
    priceJPY: 170000,
    imageUrl: '/images/rings/heartisland-tropical-scroll.jpg',
    originalUrl: 'https://heartisland.jp/collection.html',
    materials: ['Pt900', 'K18WG', 'K18PG', 'K18YG', 'K10'],
    featured: false,
  },
  {
    slug: 'heartisland-kaleikini',
    brandSlug: 'heart-island',
    nameEn: 'Kaleikini',
    nameJa: 'カレイキニ',
    nameZh: '卡萊吉尼',
    category: 'marriage',
    conceptJa: '力強い波のように、ふたりの絆はゆるがない',
    conceptZh: '如洶湧的浪潮，兩人的羈絆堅不可摧',
    descJa: '力強いうねりを表現したカレイキニ。どんな困難にも揺るがないふたりの絆を、ダイナミックな彫りで刻む。',
    descZh: '表現洶湧波濤的卡萊吉尼，以動感的雕刻刻下不畏任何困難的兩人羈絆。',
    priceJPY: 290000,
    imageUrl: '/images/rings/heartisland-kaleikini.jpg',
    originalUrl: 'https://heartisland.jp/collection.html',
    materials: ['Pt900', 'K18WG', 'K18PG', 'K18YG', 'K10'],
    featured: false,
  },
  {
    slug: 'heartisland-heritage',
    brandSlug: 'heart-island',
    nameEn: 'Heritage',
    nameJa: 'ヘリテイジ',
    nameZh: '傳承',
    category: 'marriage',
    conceptJa: '時を超えて受け継がれる、永遠なる想いのかたち',
    conceptZh: '跨越時空傳承的，永恆思念的形狀',
    descJa: '伝統的なハワイアンモチーフを継承するヘリテイジ。世代を超えて受け継がれる愛と誓いを表現した格調高いデザイン。',
    descZh: '繼承傳統夏威夷主題的傳承系列，表達跨越世代傳遞的愛與誓言，格調高雅的設計。',
    priceJPY: 220000,
    imageUrl: '/images/rings/heartisland-heritage.jpg',
    originalUrl: 'https://heartisland.jp/collection.html',
    materials: ['Pt900', 'K18WG', 'K18PG', 'K18YG', 'K10'],
    featured: false,
  },
  {
    slug: 'heartisland-maile-lei',
    brandSlug: 'heart-island',
    nameEn: 'Maile Lei',
    nameJa: 'マイレレイ',
    nameZh: '馬伊雷花環',
    category: 'marriage',
    conceptJa: '縁結びのマイレの葉が、ふたりの縁を永遠に結ぶ',
    conceptZh: '結緣的馬伊雷葉，永遠繫結兩人的緣分',
    descJa: 'ハワイで縁結びの象徴とされるマイレの葉をモチーフに。ふたりが出会い結ばれた縁を永遠に守るリング。',
    descZh: '以夏威夷象徵結緣的馬伊雷葉為主題，永遠守護兩人相遇結緣的戒指。',
    priceJPY: 290000,
    imageUrl: '/images/rings/heartisland-maile-lei.jpg',
    originalUrl: 'https://heartisland.jp/collection.html',
    materials: ['Pt900', 'K18WG', 'K18PG', 'K18YG', 'K10'],
    featured: false,
  },
  {
    slug: 'heartisland-plumeria-bouquet',
    brandSlug: 'heart-island',
    nameEn: 'Plumeria Bouquet',
    nameJa: 'プルメリアブーケ',
    nameZh: '雞蛋花花束',
    category: 'marriage',
    conceptJa: 'ハワイの花プルメリアが、親愛の想いを咲かせる',
    conceptZh: '夏威夷之花雞蛋花，讓親愛的心意盛開',
    descJa: 'ハワイを代表するプルメリアの花をブーケ状に配したデザイン。愛する人への親愛と感謝を、花々が語りかける。',
    descZh: '將代表夏威夷的雞蛋花束狀排列的設計，花朵訴說著對愛人的親愛與感謝。',
    priceJPY: 170000,
    imageUrl: '/images/rings/heartisland-plumeria-bouquet.jpg',
    originalUrl: 'https://heartisland.jp/collection.html',
    materials: ['Pt900', 'K18WG', 'K18PG', 'K18YG', 'K10'],
    featured: false,
  },
  {
    slug: 'heartisland-mauloa',
    brandSlug: 'heart-island',
    nameEn: 'Mauloa',
    nameJa: 'マウロア',
    nameZh: '永遠',
    category: 'marriage',
    conceptJa: 'マウロア——永遠。誓いは、時間をこえる',
    conceptZh: 'Mauloa——永遠。誓言，超越時間',
    descJa: 'ハワイ語で「永遠」を意味するマウロア。シンプルながら深い意味を持つ彫りが、永遠の誓いをリングに宿す。',
    descZh: '夏威夷語「永遠」之意的Mauloa，看似簡約卻寓意深遠的雕刻，讓永恆的誓言住進戒指。',
    priceJPY: 170000,
    imageUrl: '/images/rings/heartisland-mauloa.jpg',
    originalUrl: 'https://heartisland.jp/collection.html',
    materials: ['Pt900', 'K18WG', 'K18PG', 'K18YG', 'K10'],
    featured: false,
  },
  {
    slug: 'heartisland-kanaloa',
    brandSlug: 'heart-island',
    nameEn: 'Kanaloa',
    nameJa: 'カナロア',
    nameZh: '卡納洛阿',
    category: 'marriage',
    conceptJa: '水の神様カナロアが守る、深く静かな愛の誓い',
    conceptZh: '水神卡納洛阿守護的，深沉靜謐的愛的誓言',
    descJa: 'ハワイの海の神様カナロアをモチーフにした最高峰コレクション。深海のような静けさと力強さを兼ね備えた、最も格調高い彫りデザイン。',
    descZh: '以夏威夷海神卡納洛阿為主題的頂級系列，兼具深海般的靜謐與力量，最高格調的雕刻設計。',
    priceJPY: 310000,
    imageUrl: '/images/rings/heartisland-kanaloa.jpg',
    originalUrl: 'https://heartisland.jp/collection.html',
    materials: ['Pt900', 'K18WG', 'K18PG', 'K18YG', 'K10'],
    featured: false,
  },
];

// ──────────────────────────────
// ヘルパー関数
// ──────────────────────────────

/** ブランドslugでフィルタリング */
export function getRingsByBrand(brandSlug: string): Ring[] {
  return rings.filter((r) => r.brandSlug === brandSlug);
}

/** カテゴリでフィルタリング */
export function getRingsByCategory(category: Ring['category']): Ring[] {
  return rings.filter((r) => r.category === category);
}

/** スラッグから取得 */
export function getRingBySlug(slug: string): Ring | undefined {
  return rings.find((r) => r.slug === slug);
}

/** ブランド×カテゴリでフィルタリング */
export function getRingsByBrandAndCategory(
  brandSlug: string,
  category: Ring['category'],
): Ring[] {
  return rings.filter((r) => r.brandSlug === brandSlug && r.category === category);
}
